### ISSUE TITLE
Exception raised with CTkMessagebox

### ISSUE THREAD

**Issue by avalon60** [Akascape/CTkMessagebox#13]
Hi. I am trying to migrate to using CTkMessagebox.

Here is the code segment:

```
        if self._json_state == 'dirty':
            confirm = CTkMessagebox(master=self.ctk_control_panel,
                                    title='Confirm Action',
                                    message=f'You have unsaved changes. Do you wish to save these before quitting?',
                                    option_1='Cancel',
                                    option_2='Yes',
                                    option_3='No')
            if confirm.get() == 'Cancel':
                return
            elif confirm.get() == 'Yes':
                self._save_theme()
```
The pop-up renders fine:

![image](https://user-images.githubusercontent.com/89534395/234663857-456937aa-935c-46d8-9a9c-7e9dcdfc6054.png)

However, when I click the 'No' button, I get the exception:

```
  File "/home/clive/PycharmProjects/ctk5_theme_builder/lib/ctk_messagebox/ctkmessagebox.py", line 181, in get
    self.master.wait_window(self)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 696, in wait_window
    self.tk.call('tkwait', 'window', window._w)
_tkinter.TclError: bad window path name ".!ctkmessagebox"
```

The exception seems to be triggered on the second to last line:
`
elif confirm.get() == 'Yes':`

Am I doing something wrong?

Thanks,

Clive

**Comment by Akascape** [comment]
@avalon60 `.get()` can only be used once. (Just like `ctk input dialog`.
So store it as a variable first.
```python
response = messagebox.get()
...
```

**Comment by avalon60** [comment]
> @avalon60 `.get()` can only be used once. (Just like `ctk input dialog`. So store it in a variable first.
> 
> ```python
> response = confirm.get()
> if response == 'Cancel':
>             return
> elif response == 'Yes':
>             self._save_theme()
> ```

Yes, that's what I did for a workaround. I was hoping there might be a way to avoid this. If not then it's something I'll just have to workaround. The widget looks so good, it's worth it. It just seems less streamlined having to do that. Presumably the Python garbage collector doing it's thing.
