### ISSUE TITLE
Button order

### ISSUE THREAD

**Issue by avalon60** [Akascape/CTkMessagebox#14]
Is it possible to fix the button order. It seems counter intuitive that the button for option 1 is rendered in the last position and the 3rd option button is rendered first.

Thanks.

**Comment by avalon60** [comment]
But the point is that it's not intuitive. You would naturally expect that option 1 appears first, followed by option 2...
we read left to right, we write increasing sequences of numbers lower to higher, left to right...

**Comment by BenjaminTGa** [comment]
Yes, I agree with @avalon60. I get that the programmer could simply reverse the parameters, but that feels so counterintuitive.

**Comment by Akascape** [comment]
@BenjaminTGa I can change that, I will not swap the values but try to implement another argument called `options` where you can pass a list.

**Comment by BenjaminTGa** [comment]
@Akascape  Ok great!

**Comment by Akascape** [comment]
@avalon60 @BenjaminTGa 
I have updated the package...
Now use `options=["1","2","3"]` and it will draw the button in correct order.
