### ISSUE TITLE
title bar buttons do not match windows style

### ISSUE THREAD

**Issue by sukhov-andrii** [Akascape/CTkMessagebox#15]
From library desription, CTkMessagebox is designed to be used with customtkinter. However, the title bar close_button of your messagebox looks similar to the MacOS close button, even on Windows. I hope you can consider adding standart "x" button for Windows in future updates.

Thanks.

**Comment by Akascape** [comment]
Ok, I will try to add that button style.
You can add `cancel_button_color="transparent"` in order to hide that red button. You can then get the original top header by using `header=True`.

**Comment by sukhov-andrii** [comment]
Hey, thanks for the quick response! It is good to hear that you are considering my proposition. 
By the way, thanks for the tips. I just tried them out, and they actually work perfectly for me.

**Comment by Akascape** [comment]
@sukhov-andrii I added the cancel button, now it looks better:

![Screenshot](https://github.com/Akascape/CTkMessagebox/assets/89206401/6d92106e-27c7-4ccd-b16b-06a48d2b62f5)

Use `cancel_button="cross"` in the messagebox parameters.

**Comment by sukhov-andrii** [comment]
This looks awesome, @Akascape. Great job!
