### ISSUE TITLE
Enhancement: button position

### ISSUE THREAD

**Issue by pcroland** [Akascape/CTkMessagebox#27]
I think the default behaviour should be buttons in the middle, it looks really weird at the right side in my opinion.

**Comment by Akascape** [comment]
@pcroland So, do you feel these message boxes are also weird looking?
`Windows default messageboxes`
![screenshot](https://i.stack.imgur.com/q93fW.jpg)
`Mac os default messageboxes`
![screenshot](https://i.stack.imgur.com/XH2Yj.png)

It differs by OS taste. Most of the users prefer the right side in my opinion.

I guess you are on linux and used to this messagebox:

![](https://cdn.educba.com/academy/wp-content/uploads/2020/03/Tkinter-Messagebox-1.png)

**Comment by Akascape** [comment]
@pcroland But don't worry, I will add an option to justify this position of button to `left/right/center`

**Comment by Akascape** [comment]
@pcroland But don't worry, I will add an option to justify the position of buttons to `left/right/center`, but the default will be right.

**Comment by pcroland** [comment]
Yeah, they do look weird :D

**Comment by Akascape** [comment]
@pcroland I have added this new option: `justify="center"`. Update to the latest version to use this.
![Screenshot](https://github.com/Akascape/CTkMessagebox/assets/89206401/c3d11ad4-55b5-43ce-900e-3085175a867c)

You can also pass `header=True` to bring the classic look:
![Screenshot](https://github.com/Akascape/CTkMessagebox/assets/89206401/d412ceea-0790-4596-b154-b6de885fbb2e)

**Comment by pcroland** [comment]
Pretty cool, thanks.
