### ISSUE TITLE
Enhancement: remove window rounding or add proper aliasing

### ISSUE THREAD

**Issue by pcroland** [Akascape/CTkMessagebox#28]
The rounding doesn't really look nice without aliasing. Does it have proper aliasing on other OSs? I'm using Windodws 10

**Comment by Akascape** [comment]
First of all, antialiasing is not directly supported in tkinter. Specially on windows, the canvas lines are always a little jagged. I have also noticed that macosx tkinter lines looks more smoother than windows one. 

So for now, you can just use `corner_radius=0` to remove the rounding.
