### ISSUE TITLE
CTkMessagebox doesn't use master's icon.

### ISSUE THREAD

**Issue by pcroland** [Akascape/CTkMessagebox#30]
```py
app = customtkinter.CTk()
app.title("Jótállás-generátor")
app.wm_iconbitmap(os.path.join(RESOURCES, "icon.ico"))
app.minsize(780, 320)
app.maxsize(780, 320)
```
I have an icon setup like this and I use CTkMessagebox with lines like this:
```py
CTkMessagebox(title="", message="Hibás sablon!", icon="cancel", corner_radius=0, master=app)
```
And this is how a CTkMessagebox looks like on taskbar:
![img](https://telegra.ph//file/9f98759b434a4f93ab862.png)
Is there a way to set CTKMessagebox to use the master app's icon?

**Comment by Akascape** [comment]
@pcroland You have to apply the icon just like in a ctktoplevel.

```python
import os
from PIL import ImageTk
...

iconpath = ImageTk.PhotoImage(file=os.path.join("assets","logo.png"))

msg = CTkMessagebox(root, title='', message='hello')
msg.wm_iconbitmap()
msg.after(300, lambda: msg.iconphoto(False, iconpath))
```

There is a issue in customtkinter toplevels related to the icon, that is why you have to apply this method.

**Comment by Akascape** [comment]
In the next update I will add the message icon as the window icon.

**Comment by pcroland** [comment]
Thanks. I added a hook to PyInstaller btw, so you won't need to use `--add-data` in the future fir CTkMessagebox: https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/619/commits
(Someone did it for customtkinter too last month.)

**Comment by Akascape** [comment]
@pcroland oh, nice.

**Comment by Akascape** [comment]
@pcroland I fixed this issue, now the message box icon becomes the window icon,
