### ISSUE TITLE
Add input fields

### ISSUE THREAD

**Issue by Ulmerju** [Akascape/CTkMessagebox#31]
Is it possible to add simple modal dialogs to get a value from the user.

for example:

> askfloat(title, prompt, **kw)
> askinteger(title, prompt, **kw)
> askstring(title, prompt, **kw)

It would be ideal to do it based on Tkinter Dialogs.

**Comment by Akascape** [comment]
No, it is a messagebox like tkinter. Instead make your own input dialog using ctktoplevel.
