### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by avalon60** [Akascape/CTkMessagebox#36]
Hey @Akascape , it would be great if there was an option to ring the system bell, when the message window pops up. This would be handy for serious error situations.

**Comment by Akascape** [comment]
@avalon60 yeah, it will be great, I will try to add this if possible.

**Comment by avalon60** [comment]
I think there is a bell() function to do this.

**Comment by Akascape** [comment]
@avalon60 
Yeah, bell() function makes the default windows sound. I will implement a bell parameter for this. But what should be the default for this parameter (True or False)?

**Comment by Akascape** [comment]
@avalon60 
Yeah, bell() function makes the default windows sound. I will implement a bell parameter for this. But can you suggest the default for this? (True/False type parameter)

**Comment by avalon60** [comment]
@Akascape, I would say that the default should be False. Otherwise a lot of updates to existing applicationm code might be required. Backwards compatibility should take precedence.

**Comment by Akascape** [comment]
@avalon60 Ok, I added this feature. Now you can pass `sound=True` parameter to enable it. Thanks!
