### ISSUE TITLE
CTkMessagebox and set_appearance_mode

### ISSUE THREAD

**Issue by titus483** [Akascape/CTkMessagebox#40]
CTkMessage box seems to have a problem evaluating the customtkinter.set_appearance_mode function.
On my system (Win11, Python 3.10.64) the examples delivered with CTkMessagebox all work perfectly.
In my own app CTkMessagebox works as expected if I use ctk.set_appearance_mode("Light") or I omit it so that "Light" is the 
default.
 But as soon as I use ctk.set_appearance_mode("Dark") it fails. I'm not able to create a minimal example right now.
The code starts:
    import tkinter as tk
    from tkinter import ttk
    import customtkinter as ctk
    from CTkMessagebox import CTkMessagebox
    ...
    class Converter():
    def __init__(self):
        super().__init__()
         self.win = ctk.CTk()
         ctk.set_appearance_mode("Dark")  # or "Light"
    ...
In both cases the base window appears as expected, whereas the messagebox is ok for "Light" but not for "Dark":

![msgbox_dark](https://github.com/Akascape/CTkMessagebox/assets/10687436/d7b0963b-1e12-4a85-b737-ca6c478275d0)
![msgbox_light](https://github.com/Akascape/CTkMessagebox/assets/10687436/ec3d558f-3dbc-42a2-af00-afd28f3f707e)

**Comment by Akascape** [comment]
@titus483 You mean the messagebox theme doesn't change when if set the appearance mode to Dark when the messagebox is open at the moment?

**Comment by titus483** [comment]
No, I set the the appearance Mode at the beginning of the program just once - no messagebox open, not even the main window. It works for light mode, not for dark mode.

Am 17. Oktober 2023 17:29:58 MESZ schrieb Akash Bora ***@***.***>:

**Comment by titus483** [comment]
Just to be a bit more precise:
My app was developped with original tkinter (including ttk).
When it worked I migrated it to customtkinter and tested ist for both themes "dark" and "light". It worked except for the old ugly tkinter messageboxes.
Then I learnt about CTkMessagebox and replaced the old tkinter-messageboxes with CTkMessageboxes. 
This worked from the beginning for the "light" theme but not for the "dark" theme. 
In another application I had the same problem but could solve it by playing a bit with the location where I call the set_appearance_function. 
In my current app, however, this doesn't help. 
So: no switch of modes during execution - just one test for "light" (which woks fine) and one test for "dark" which doesn't work.

**Comment by titus483** [comment]
[SOLVED] In the meantime the app works as expected.
I rearranged some customtkinter-statements within the module and updated customtkinter to the latest version. 
Without being able to identify the reason exactly I'm happy that the problem seems to be solved.
