### ISSUE TITLE
Button width etc.

### ISSUE THREAD

**Issue by jxjo** [Akascape/CTkMessagebox#5]
First of all: Thank you very much for this fine extension!

Some little issues I experienced: 

- `button_width` is not working as the botton are `sticky="news"` and the column is stretched - so the buttons align to the grid cell. Maybe it's better to have a little frame_bottom for independant positioning and sizing of the buttons? 
- the CTkToplevel window should have `self.transient(master)` to be hidden together with its master window
- Could you add `button_height`? This would be super as the original CTkButtons are quite "heavy" ... (also buttons and header are stretched in height when the messagebox height is increased, which looks quite strange)

**Comment by Akascape** [comment]
@jxjo 
>button_width is not working as the botton are sticky="news" and the column is stretched - so the buttons align to the grid cell. Maybe it's better to have a little frame_bottom for independant positioning and sizing of the buttons?

Fixed the button width issue, also added button height parameter.

>the CTkToplevel window should have self.transient(master) to be hidden together with its master window

Now you can add `topmost=False` in order to disable the topmost and apply transient window.

Please update to the latest version
