### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by BhagyaJyoti22006** [Akascape/CTkMessagebox#51]
So I was frustrated why was focus_option not working as expected. Read the docs again and again. Then went to check the source code and there it was. 

the word should be option_focus. You might have figured it out still posted so one could check this issue first.

by the way, thanks a lot mate for these widgets!!!

**Comment by Akascape** [comment]
@BhagyaJyoti22006 thanks for pointing this out. I have updated the docs.
