### ISSUE TITLE
Feature request: Ability to put checkboxes inside of pop-ups

### ISSUE THREAD

**Issue by Tamzuu** [Akascape/CTkMessagebox#53]
It would be nice if it was possible to have options for the message like for the buttons where I could choose to put checkboxes there, while also keeping the buttons on the bottom to save the choice.

**Comment by Akascape** [comment]
@Tamzuu Added this feature.
```python
msg = CTkMessagebox(app)
checkbox = msg.place_widget(customtkinter.CTkCheckBox, x=10, y=150, text="Don't show again")
```
