### ISSUE TITLE
App icon is changed to message box icon in dock at the bottom in mac

### ISSUE THREAD

**Issue by zishanakhtar** [Akascape/CTkMessagebox#57]
App icon is changed to message box icon in dock at the bottom in macOS Sonoma.
Tried different versions. It works perfectly till version 2.3, issue starts in version 2.4
<img width="1440" alt="Screenshot 2024-03-22 at 9 42 36 PM" src="https://github.com/Akascape/CTkMessagebox/assets/85608604/e5ae2072-be4c-4726-b279-715109091882">

**Comment by Akascape** [comment]
@zishanakhtar It's intentional, you can change the icon of that messagebox using wm_iconbitmap method.

**Comment by zishanakhtar** [comment]
@Akascape The icon stays the same and doesn't return back to app icon even when the message box is closed by clicking on Ok button. Is that intentional too?

When app starts and message box hasn't opened yet
<img width="1440" alt="Screenshot 2024-03-22 at 10 43 55 PM" src="https://github.com/Akascape/CTkMessagebox/assets/85608604/b330f08b-6bf3-456d-a39c-7865f41d53de">

When message box opens
<img width="1440" alt="Screenshot 2024-03-22 at 9 42 36 PM" src="https://github.com/Akascape/CTkMessagebox/assets/85608604/4e414949-58db-4bcd-b476-41acffa233e9">

After the message box is closed
<img width="1440" alt="Screenshot 2024-03-22 at 10 44 42 PM" src="https://github.com/Akascape/CTkMessagebox/assets/85608604/771b923e-7024-47a0-abf7-acd7280b7392">

**Comment by Akascape** [comment]
@zishanakhtar No this is bug for sure, it should not behave like this, In windows the messagebox is totally a separate window so the change in icon doesn't affect the main window. But in macos, this is probably a bug, I will fix it.

**Comment by Akascape** [comment]
@zishanakhtar Try the new version.
