### ISSUE TITLE
Select button with keyboard arrows

### ISSUE THREAD

**Issue by Ju-plop** [Akascape/CTkMessagebox#67]
Hi,

Would it be possible to select between one button or another by using the left and right arrows of the keyboard?

Thank you!

**Comment by Akascape** [comment]
@Ju-plop Yes, it's already there. You just have to pass `option_focus=1` parameter which will focus the first button. Then you can use the left-right arrow keys to change the focus and even select the option by pressing the Enter key.

**Comment by Ju-plop** [comment]
Thank you, I had not understood that it was the purpose of option_focus.
